---
apiVersion: v1
kind: Secret

metadata:
  name: minio-server
  annotations:
    kustomize.config.k8s.io/needs-hash: "true"
    kustomize.config.k8s.io/behavior: replace

type: Opaque
stringData:
  accesskey: ENC[AES256_GCM,data:9hAoDkRvOHs=,iv:5k9Q6oiln/xSodZYM2vdEEG0cnXO8J4Fl3IPNWS3eR4=,tag:0eUm/tYAlbI7DljwmOYqMg==,type:str]
  secretkey: ENC[AES256_GCM,data:VgB6iAqhYm9qh5pJQK+ITXVqlm1ote38,iv:DiMjTIQnxNJhdNd+pikMZkB/YDoVMqg/aurwLUvCaek=,tag:jKtDdIE+RKYUkxMJZfNymQ==,type:str]

sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: "2021-10-11T21:10:23Z"
  mac: ENC[AES256_GCM,data:kzvEu4LIkxrKZ1uHOPdrGj1X+vwkBoqnpSq+vQ7VVvt62Yf0yjSHKlnnUH7xcp+iJG12rJblOzGa/dG06FI2aebRc54BKz2zWBNKVNKCvkjdENA5HZ5bp+0YTsVGTZ6FXsNVgf2DpnkdW3ndj7zaxj6n6UGw9ejRzCtRouwhqQs=,iv:vLUsrJP6IyRzEtaCsPj2Xppgsh+M0a47MKGSyihyFEI=,tag:IzQIVNfsBny1K6Zs1wIe5Q==,type:str]
  pgp:
    - created_at: "2021-10-11T21:10:23Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        wcFMA8mzLMCLLWTIARAAcCQjEOpcl7Ovd4TNm9hGJlqx7EGFSu/1v6kXkuQcjlp6
        QgnOSK/XgHJL49cNhcl3V9CCZpgGCMny5sp87BhFlsTbbjNyEqBylfW7i1OTLkOB
        TelD6WeeuwVAP9hYSAq6wneuR9/+zfbbO066XGRuAMBPyC9JK6tkih0oOIOBeXQc
        7GwHz4zkciGFGk+gAvtve72uLB+GtAQfoiDl0RARt91CkW4lq4yhxwFbRX5Pthjm
        ZYU9PwP8JoRWev9izM8P+/BHwgdAs3QxRC9QzgCE9sltRsCaFGkymZiHX0+eLr0E
        MisF+qXTXvNrZYBMtfsJd+UpsjFtbHTWgRdk+wpgL30tI+GVspo1iUGsKttNnD4E
        3zgoFXf4QaXXQpud73b4ZQ2BatoWh86QY96F6vFaR+PzY0zOQHpODaIvsZ23JTVA
        1HxYZQrnISXs9jEkg2ffYYk+9lHjPJextWopBXFfGTl0eoc5a16JuUNoL7qhsqG0
        B4AOo/PQJJMkjaF/Cz64iBXTPew1aUo1fUAhYOFn+pg/Fvcbl/x3xoLaUoebQnlV
        n6TUgsxMTI8mje79qjnXYvwkWxlmCuGM3tU9zxq/NpcJWJTRzMqc2bQbpaem45u9
        l8+tmd7Zvsc60m2T8QYBWh8UEskT0KMOQYkUgtg/EDRy9Sv6mKzBi/ZprEpfdI3S
        5gG82q/fdt3mnE63BqVZmujBg9IMcNmhTEj7gx8V356g8vuuaM948Vj2EHBSs+fN
        dxVIe021+3HQO1Mxp7yeobPkJCZ5UP4V4Q1Axa2Ch3ewO+LaiPsHAA==
        =3WnL
        -----END PGP MESSAGE-----
      fp: EF151CCB8887F610C78430847ABE0A09C4825149
  encrypted_regex: ^(data|stringData)$
  version: 3.7.1

...
