- hosts: servers
  roles:
    - base
    - hosts
    - gai
    - sysctl
    - sudo
    - root
    - motd
    - nullmailer
    - firewall
    - docker
    - users
    - traefik
    - telegraf

- hosts: iring
  roles:
    - minio
    - downloads
    - mariadb
    - drone
    - scaler
